services:
  # A Docker web service
  - type: web
    name: esgi.render.nodejs-esgi.render.nodejs
    runtime: node
    branh: main
    buildcommand: npm install
    startCommand: npm start
    envVars:
      -key: DATABASE_URL
        fromDatabase:
          name: data_base
          property: connectionString

      
    databases:
      - name: data_base
        plan: free
