services:
  # A Docker web service
  - type: web
    name: esgi.render.nodejs-esgi.render.nodejs
    runtime: node
    branh: main
    buildcommand: npm install
    startCommand: npm run start
    region: frankfurt
    plan: free
    
    envVars:
      -key: DATABASE_URL
        fromDatabase:
          name: tp3cloud
          property: connectionString

      
databases:
  - name: tp3Cloud
    region: frankfurt
    plan: free
